# Generated by Django 5.2.14 on 2026-06-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_merge_20241124_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedrun',
            options={'ordering': ['event__datetime', 'order'], 'permissions': (('can_view_tech_notes', 'Can view tech notes'),), 'verbose_name': 'Speedrun'},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'verbose_name_plural': 'Runner'},
        ),
        migrations.AddField(
            model_name='event',
            name='oengus_id',
            field=models.CharField(blank=True, default='', help_text='ID or slug for Oengus event', max_length=100, verbose_name='Oengus ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('EUR', 'Euro'), ('NOK', 'Norwegian Kroner')], max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='paypalcurrency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('EUR', 'Euro'), ('NOK', 'Norwegian Kroner')], default='USD', max_length=8, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='platform',
            field=models.CharField(choices=[('TWITCH', 'Twitch'), ('MIXER', 'Mixer'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube')], default='TWITCH', help_text='Streaming Platforms', max_length=20),
        ),
        migrations.AlterField(
            model_name='talent',
            name='pronouns',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
